name: Deploy C++ Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to VM
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        VM_USER: ${{ secrets.VM_USER }}
        VM_IP: ${{ secrets.VM_IP }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $VM_IP >> ~/.ssh/known_hosts
        
        # Create directory if it does not exist
        ssh -i ~/.ssh/id_rsa $VM_USER@$VM_IP 'mkdir -p /repo/server/include'

        # Copy files to VM
        scp -i ~/.ssh/id_rsa server.cpp $VM_USER@$VM_IP:/repo/server/
        scp -i ~/.ssh/id_rsa include/Logger.hpp $VM_USER@$VM_IP:/repo/server/include
        scp -i ~/.ssh/id_rsa setup_server.sh $VM_USER@$VM_IP:/repo/server
        
        # SSH commands to inspect current server state before running setup
        ssh -i ~/.ssh/id_rsa $VM_USER@$VM_IP '
          echo "============ Current System State ============"
          echo "Checking for processes using port 8443:"
          sudo lsof -i:8443 || echo "No process using port 8443"
          
          echo "Checking server processes:"
          ps aux | grep server | grep -v grep || echo "No server processes found"
          
          echo "Checking service status:"
          sudo systemctl status grabbiel-server || echo "Service not found"
          sudo systemctl status apache2 || echo "Apache not found"
          
          echo "===========================================" 
          
          # Run setup script with debugging enabled
          cd /repo/server && \
          chmod +x setup_server.sh && \
          sudo bash -x ./setup_server.sh
        '
